//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FittyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> gearId { get; set; }
        public Nullable<int> sportsWearId { get; set; }
        public string userId { get; set; }
        public Nullable<int> orderId { get; set; }
    }
}
