//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FittyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string userId { get; set; }
        public string pass { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public string emailId { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string role { get; set; }
    }
}
